/* USE THIS SCRIPT TO CREATE TICKETS DATABASE TABLES */

CREATE TABLE IF NOT EXISTS ticket
(id INT NOT NULL PRIMARY KEY,
userId INT NULL);

CREATE TABLE IF NOT EXISTS usert
(id INT NOT NULL PRIMARY KEY,
username VARCHAR(50) NULL);

ALTER TABLE ticket ADD FOREIGN KEY (userId) REFERENCES usert(id);
